### ISSUE TITLE
Local Data Lock: Tests - Not able to register local account

### ISSUE THREAD

**Issue by dejan-milicevic** [mylofi/local-data-lock#10]
I am not able to register local account on the test page https://mylofi.github.io/local-data-lock/

**Comment by getify** [comment]
what device are you using? what kind of biometric passkey does it support (faceid, touchid, etc)?

**Comment by dejan-milicevic** [comment]
Currently I'm using an old MacBook Pro from 2012, macOS Catalina version 10.15.7.

**Comment by dejan-milicevic** [comment]
No, it's asking to touch the security key, but I don't have that option on my computer.
<img width="481" alt="image" src="https://github.com/user-attachments/assets/578719d5-5c6c-489d-b57e-339af52bb6c5">

**Comment by getify** [comment]
So there's your answer. Your device doesn't support passkeys. Sorry about that.
